bot:
  token: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
  username: "mygrokbot"

grok:
  api_key: "xai-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  api_url: "https://api.x.ai/v1/chat/completions"
  model: "grok-beta"

db:
  path: "/data/bot.db"

logging:
  debug: true